// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/communication/social_media.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocialMediaPlatform int32

const (
	SocialMediaPlatform_PLATFORM_UNSPECIFIED SocialMediaPlatform = 0
	SocialMediaPlatform_PLATFORM_INSTAGRAM   SocialMediaPlatform = 1
	SocialMediaPlatform_PLATFORM_LINKEDIN    SocialMediaPlatform = 2
	SocialMediaPlatform_PLATFORM_WHATSAPP    SocialMediaPlatform = 3
)

// Enum value maps for SocialMediaPlatform.
var (
	SocialMediaPlatform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_INSTAGRAM",
		2: "PLATFORM_LINKEDIN",
		3: "PLATFORM_WHATSAPP",
	}
	SocialMediaPlatform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_INSTAGRAM":   1,
		"PLATFORM_LINKEDIN":    2,
		"PLATFORM_WHATSAPP":    3,
	}
)

func (x SocialMediaPlatform) Enum() *SocialMediaPlatform {
	p := new(SocialMediaPlatform)
	*p = x
	return p
}

func (x SocialMediaPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SocialMediaPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_communication_social_media_proto_enumTypes[0].Descriptor()
}

func (SocialMediaPlatform) Type() protoreflect.EnumType {
	return &file_proto_communication_social_media_proto_enumTypes[0]
}

func (x SocialMediaPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SocialMediaPlatform.Descriptor instead.
func (SocialMediaPlatform) EnumDescriptor() ([]byte, []int) {
	return file_proto_communication_social_media_proto_rawDescGZIP(), []int{0}
}

type SocialMedia struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform SocialMediaPlatform `protobuf:"varint,2,opt,name=platform,proto3,enum=communication.SocialMediaPlatform" json:"platform,omitempty"`
	Address  string              `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *SocialMedia) Reset() {
	*x = SocialMedia{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_social_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMedia) ProtoMessage() {}

func (x *SocialMedia) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_social_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMedia.ProtoReflect.Descriptor instead.
func (*SocialMedia) Descriptor() ([]byte, []int) {
	return file_proto_communication_social_media_proto_rawDescGZIP(), []int{0}
}

func (x *SocialMedia) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialMedia) GetPlatform() SocialMediaPlatform {
	if x != nil {
		return x.Platform
	}
	return SocialMediaPlatform_PLATFORM_UNSPECIFIED
}

func (x *SocialMedia) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_communication_social_media_proto protoreflect.FileDescriptor

var file_proto_communication_social_media_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x77, 0x0a, 0x0b, 0x53, 0x6f, 0x63, 0x69, 0x61,
	0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x2a, 0x75, 0x0a, 0x13, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x4c, 0x41, 0x54, 0x46,
	0x4f, 0x52, 0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x49, 0x4e,
	0x53, 0x54, 0x41, 0x47, 0x52, 0x41, 0x4d, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x4c, 0x41,
	0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x4c, 0x49, 0x4e, 0x4b, 0x45, 0x44, 0x49, 0x4e, 0x10, 0x02,
	0x12, 0x15, 0x0a, 0x11, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x57, 0x48, 0x41,
	0x54, 0x53, 0x41, 0x50, 0x50, 0x10, 0x03, 0x42, 0x21, 0x5a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_communication_social_media_proto_rawDescOnce sync.Once
	file_proto_communication_social_media_proto_rawDescData = file_proto_communication_social_media_proto_rawDesc
)

func file_proto_communication_social_media_proto_rawDescGZIP() []byte {
	file_proto_communication_social_media_proto_rawDescOnce.Do(func() {
		file_proto_communication_social_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_communication_social_media_proto_rawDescData)
	})
	return file_proto_communication_social_media_proto_rawDescData
}

var file_proto_communication_social_media_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_communication_social_media_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_communication_social_media_proto_goTypes = []interface{}{
	(SocialMediaPlatform)(0), // 0: communication.SocialMediaPlatform
	(*SocialMedia)(nil),      // 1: communication.SocialMedia
}
var file_proto_communication_social_media_proto_depIdxs = []int32{
	0, // 0: communication.SocialMedia.platform:type_name -> communication.SocialMediaPlatform
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_communication_social_media_proto_init() }
func file_proto_communication_social_media_proto_init() {
	if File_proto_communication_social_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_communication_social_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialMedia); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_communication_social_media_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_communication_social_media_proto_goTypes,
		DependencyIndexes: file_proto_communication_social_media_proto_depIdxs,
		EnumInfos:         file_proto_communication_social_media_proto_enumTypes,
		MessageInfos:      file_proto_communication_social_media_proto_msgTypes,
	}.Build()
	File_proto_communication_social_media_proto = out.File
	file_proto_communication_social_media_proto_rawDesc = nil
	file_proto_communication_social_media_proto_goTypes = nil
	file_proto_communication_social_media_proto_depIdxs = nil
}
